### PR TITLE
Add --pipeline to the wercker --help visible output

### PR DESCRIPTION
**Pull request by nathan-grant**
Small change to flags to add cli visible help for the pipeline flag. #234

### CODE REVIEW

**Comment by faiq** [comment]
looking good cc: @hatchan for review

**Comment by hatchan** [comment]
Think we just need to remove the Hidden flag from this argument: https://github.com/wercker/wercker/blob/master/cmd/flags.go#L74-L75

**Comment by faiq** [comment]
looks good

**Comment by hatchan** [comment]
@nathan-grant Thanks 👍

**Comment by hatchan** [comment]
Implemented for ferengi branch: e0f1e668f4cfb00aa1d0f283e30fffe8e730e677

**Pull request merged**
