### PR TITLE
attempts to solve #158

### PR DESCRIPTION
**Pull request by mwhooker**

### CODE REVIEW

**Comment by mwhooker** [comment]
works how I would expect it to work:

```
../wercker/wercker/wercker --environment my.env build --pipeline build .
--> No Docker host specified, checking: /var/run/docker.sock
--> Executing pipeline
--> Running step: setup environment
Pulling from library/alpine: latest
Already exists: d0ca440e8637
Digest: sha256:f655166f57d91bdfc8b3bc75a20391b7516de9f48ca761249c185fcb022124d2
Status: Image is up to date for alpine:latest
--> Running step: wercker-init
--> Running step: test
BAZfoo'bar
foo'bar
--> Steps passed: 2.45s
--> Pipeline finished: 3.45s
$ cat my.env
X_FOO=BAZ$BAR
X_BAR=foo'bar
$ cat wercker.yml
box:
    id: alpine:latest
    cmd: /bin/sh
build:
    steps:
        - script:
            name: test
            code: |
                echo $FOO
                echo $BAR
```

**Comment by mwhooker** [comment]
Looks like it's working to me...

```
$ $GOPATH/src/github.com/wercker/wercker/wercker --environment my.env build --pipeline build .
--> No Docker host specified, checking: /var/run/docker.sock
--> Executing pipeline
--> Running step: setup environment
Pulling from library/alpine: latest
Already exists: d0ca440e8637
Digest: sha256:f655166f57d91bdfc8b3bc75a20391b7516de9f48ca761249c185fcb022124d2
Status: Image is up to date for alpine:latest
--> Copying source to container
--> Running step: wercker-init
--> Running step: test
FOO$BAR
foo'bar
--> Steps passed: 2.69s
--> Pipeline finished: 3.69s

$ cat my.env
X_FOO=FOO$BAR
X_BAR=foo'bar

$ cat wercker.yml
box:
    id: alpine:latest
    cmd: /bin/sh
build:
    steps:
        - script:
            name: test
            code: |
                echo $FOO
                echo $BAR
```

**Comment by faiq** [comment]
this does make sense overall

quoting this from [here](http://mywiki.wooledge.org/Quotes)

> Single quotes: '...' removes the special meaning of every character between the quotes. The only character that you can't safely enclose in single quotes is a single quote.

and then the second part of the change is substituting any single quotes with '"'"' which ends up getting interpreted as a single quote when used later on 

👍

**Comment by termie** [comment]
the substitution hurts my brain but seems on the up and up

**Comment by hatchan** [comment]
Do not use single quotes, any env var in there won't be resolved in the export anymore.

**Comment by termie** [comment]
i think this issue is actually up the stack from us, we want the stuff to get interpreted at this stage, it's the shell-script setting up the environment that is having issues, i'll try applying this fix to kiddie-pool instead

**Comment by termie** [comment]
actually i don't know still processing

**Comment by termie** [comment]
yeah i think the up the stack is correct, it looks like the thing that interprets the ENVIRONMENT file cares about "#" so quoting in the environment file is enough for part of it, but... there is some weird behavior re: variable interpretation i'm thinking a race condition on the ordering of things

**Comment by termie** [comment]
like, these exports don't come out in the order expected so it is tough to do references within them, so there are two pieces to the fix:
1. quoting when we generate the environment file (i'll do that in k-pool)
2. making order deterministic if possible, 
3. towards the specific issue in #158 we have to tell them to `disable-sync: true` in the docker push step because the environment gets loaded from the shell right before that step gets parsed and the shell interprets the $ pretty much regardless of anything we do

**Comment by alphaaddynamo** [comment]
this was closed but the problem was not solved and #158 is still open

**Pull request closed without merging**
